[[social]]
  identifier = "github"
  name       = "GitHub"
  weight     = 1
  url        = "https://github.com/18235859453"
  [social.params]
    icon = "brand-github"

[[social]]
  identifier = "bilibili"
  name       = "Bilibili"
  weight     = 2
  url        = "https://space.bilibili.com/513520210"
  [social.params]
    icon = "brand-bilibili"

[[social]]
  identifier = "douyin"
  name       = "Douyin"
  weight     = 3
  url        = "https://v.douyin.com/lG7AFwFJFMA/"
  [social.params]
    icon = "brand-douyin"
