mainSections = ["post"]
rssFullContent = true
favicon = "img/avatar.jpg"

[footer]
  since = 2026

[sidebar]
  avatar = "img/avatar.jpg"
  subtitle = "记录学习与思考"

[article]
  [article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
  homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } },
  ]
  page = [{ type = "toc" }]

[comments]
  enabled  = true
  provider = "giscus"

  [comments.giscus]
    repo             = "18235859453/self-site"
    repoID           = "R_kgDOSliSnQ"
    category         = "General"
    categoryID       = "DIC_kwDOSliSnc4C9qaS"
    mapping          = "title"
    lightTheme       = "light"
    darkTheme        = "dark_dimmed"
    reactionsEnabled = 1
    emitMetadata     = 0
    inputPosition    = "top"
    lang             = "zh-CN"

[cookies]
  enabled = false

[colorScheme]
  toggle = true
  default = "auto"
